/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelBooking;

import HotelBooking.Database.DatabaseConn;
import Model.BookRoom;
import Model.Employee;
import Model.Room;
import Model.RoomType;
import java.awt.*;
import java.awt.event.ActionEvent;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import ClientSocket.Client;

import java.util.*;
import java.util.Date;
import java.util.List;
import java.sql.*;

/**
 *
 * @author Admin
 */
public class AdminFrame extends javax.swing.JFrame {
    private List<BookRoom> AllBookRoom = null;
    private List<Employee> AllEmployee = null;
    private List<RoomType> roomtypes = null;
    private List<Room> AllRoom;
    Client clientSocket = new Client();

    /**
     * Creates new form EmployeeFrame
     */
    public AdminFrame() {
        initComponents();
        this.UpdateDashboard();
    }

    public void updateTablesPage() {
        this.AllRoom = clientSocket.getRooms();
        this.roomtypes = clientSocket.getRoomTypes();

        while (RoomTable.getRowCount() > 0) {
            ((DefaultTableModel) RoomTable.getModel()).removeRow(0);
        }
        DefaultTableModel model = (DefaultTableModel) RoomTable.getModel();

        for (Room r : AllRoom) {
            model.addRow(new Object[] { r.RoomNo, r.RoomTypeName, r.RoomTypePrice, r.checked });
        }

        RoomTypeComboBox.removeAllItems();
        roomtypes.forEach((temp) -> {
            RoomTypeComboBox.addItem(new ComboItem(temp.RoomTypeName, temp));
        });
    }

    public void UpdateDashboard() {
        this.AllBookRoom = clientSocket.getBooking();

        while (AllBookingTable.getRowCount() > 0) {
            ((DefaultTableModel) AllBookingTable.getModel()).removeRow(0);
        }

        DefaultTableModel model = (DefaultTableModel) AllBookingTable.getModel();

        for (BookRoom b : this.AllBookRoom) {
            model.addRow(new Object[] { b.FirstName, b.LastName, b.Age, b.PhoneNumber, b.DateCheckedIn,
                    b.DateCheckedOut, b.RoomNo, b.RoomTypeName, b.RoomTypePrice, b.payment });
        }

        List<Integer> data = clientSocket.Report();
        this.TotalRooms.setText(String.valueOf(data.get(0)));
        this.TotalBooked.setText(String.valueOf(data.get(1)));
        this.TotalPayment.setText(String.valueOf(data.get(2)));
    }

    public void UpdateDashboardTable() {
        Date start = this.StartingDate.getDate();
        Date end = this.EndingDate.getDate();
        if (start != null && end != null) {
            this.AllBookRoom = clientSocket.getInfoInterval(start, end);
            while (AllBookingTable.getRowCount() > 0) {
                ((DefaultTableModel) AllBookingTable.getModel()).removeRow(0);
            }

            DefaultTableModel model = (DefaultTableModel) AllBookingTable.getModel();

            for (BookRoom b : this.AllBookRoom) {
                model.addRow(new Object[] { b.FirstName, b.LastName, b.Age, b.PhoneNumber, b.DateCheckedIn,
                        b.DateCheckedOut, b.RoomNo, b.RoomTypeName, b.RoomTypePrice, b.payment });
            }
        } else if (start == null && end == null) {
            this.AllBookRoom = clientSocket.getBooking();

            while (AllBookingTable.getRowCount() > 0) {
                ((DefaultTableModel) AllBookingTable.getModel()).removeRow(0);
            }

            DefaultTableModel model = (DefaultTableModel) AllBookingTable.getModel();

            for (BookRoom b : this.AllBookRoom) {
                model.addRow(new Object[] { b.FirstName, b.LastName, b.Age, b.PhoneNumber, b.DateCheckedIn,
                        b.DateCheckedOut, b.RoomNo, b.RoomTypeName, b.RoomTypePrice, b.payment });
            }
        } else {
            JOptionPane.showMessageDialog(null, "Both Starting and ending Date Must Be Provided", "Error Message", 1);
            this.StartingDate.setDate(null);
            this.EndingDate.setDate(null);
        }

    }

    public void updateEmployee() {
        this.AllEmployee = clientSocket.getEmployees();

        while (EmployeeTable.getRowCount() > 0) {
            ((DefaultTableModel) EmployeeTable.getModel()).removeRow(0);
        }

        DefaultTableModel model = (DefaultTableModel) EmployeeTable.getModel();

        for (Employee e : this.AllEmployee) {
            model.addRow(new Object[] { e.EmployeeUsername, e.EmployeePasswod });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        OptionPanel = new javax.swing.JPanel();
        EmployeeNav = new javax.swing.JButton();
        reportNav = new javax.swing.JButton();
        RoomsNav = new javax.swing.JButton();
        ProfileNav = new javax.swing.JButton();
        PagesPanel = new javax.swing.JPanel();
        ReportPage = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        FirstNameLabel10 = new javax.swing.JLabel();
        EndingDate = new org.jdesktop.swingx.JXDatePicker();
        FirstNameLabel12 = new javax.swing.JLabel();
        StartingDate = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane3 = new javax.swing.JScrollPane();
        AllBookingTable = new javax.swing.JTable();
        TotalRooms = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TotalBooked = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TotalPayment = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ClearDateButton = new javax.swing.JButton();
        GoButton = new javax.swing.JButton();
        EmployeePage = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        FirstNameLabel = new javax.swing.JLabel();
        EmployeeRenameUsername = new javax.swing.JTextField();
        FirstNameLabel1 = new javax.swing.JLabel();
        EmployeePassword = new javax.swing.JTextField();
        RegisterEmployee = new javax.swing.JButton();
        FirstNameLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        FirstNameLabel2 = new javax.swing.JLabel();
        FirstNameLabel7 = new javax.swing.JLabel();
        EmployeeUsername = new javax.swing.JTextField();
        DeleteEmployee = new javax.swing.JButton();
        FirstNameLabel11 = new javax.swing.JLabel();
        RoomsPage = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RoomTypeComboBox = new javax.swing.JComboBox<>();
        AddRoom = new javax.swing.JButton();
        RoomNoField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoomTable = new javax.swing.JTable();
        ProfilePage = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        AdminUpdate = new javax.swing.JButton();
        FirstNameLabel3 = new javax.swing.JLabel();
        AdminUsername = new javax.swing.JTextField();
        FirstNameLabel8 = new javax.swing.JLabel();
        FirstNameLabel9 = new javax.swing.JLabel();
        FirstNameLabel4 = new javax.swing.JLabel();
        FirstNameLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        FirstNameLabel13 = new javax.swing.JLabel();
        AdminNewPassword = new javax.swing.JPasswordField();
        AdminOldPassword = new javax.swing.JPasswordField();
        AdminConfirmPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new java.awt.BorderLayout());

        OptionPanel.setBackground(new java.awt.Color(255, 255, 255));

        EmployeeNav.setBackground(new java.awt.Color(0, 0, 0));
        EmployeeNav.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeNav.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\HMS\\staff_64.png")); // NOI18N
        EmployeeNav.setText("Employee");
        EmployeeNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeNavActionPerformed(evt);
            }
        });

        reportNav.setBackground(new java.awt.Color(0, 0, 0));
        reportNav.setForeground(new java.awt.Color(255, 255, 255));
        reportNav.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\HMS\\report_64.png")); // NOI18N
        reportNav.setText("Report");
        reportNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportNavActionPerformed(evt);
            }
        });

        RoomsNav.setBackground(new java.awt.Color(0, 0, 0));
        RoomsNav.setForeground(new java.awt.Color(255, 255, 255));
        RoomsNav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelBooking/Assets/icons8_bed_64.png"))); // NOI18N
        RoomsNav.setText("Rooms");
        RoomsNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomsNavActionPerformed(evt);
            }
        });

        ProfileNav.setBackground(new java.awt.Color(0, 0, 0));
        ProfileNav.setForeground(new java.awt.Color(255, 255, 255));
        ProfileNav.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\HMS\\Profile_64.png")); // NOI18N
        ProfileNav.setText("Profile");
        ProfileNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileNavActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OptionPanelLayout = new javax.swing.GroupLayout(OptionPanel);
        OptionPanel.setLayout(OptionPanelLayout);
        OptionPanelLayout.setHorizontalGroup(
            OptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(reportNav, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(EmployeeNav, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(RoomsNav, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(ProfileNav, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        OptionPanelLayout.setVerticalGroup(
            OptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(OptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeNav, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportNav, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomsNav, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProfileNav, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        MainPanel.add(OptionPanel, java.awt.BorderLayout.NORTH);

        PagesPanel.setLayout(new java.awt.CardLayout());

        ReportPage.setBackground(new java.awt.Color(255, 204, 51));
        ReportPage.setMaximumSize(new java.awt.Dimension(1306, 727));
        ReportPage.setPreferredSize(new java.awt.Dimension(1000, 727));
        ReportPage.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(0, 255, 0));
        jPanel7.setOpaque(false);

        FirstNameLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel10.setText("End Date");

        FirstNameLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel12.setText("Start Date");

        StartingDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartingDateActionPerformed(evt);
            }
        });

        AllBookingTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        AllBookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "FirstName", "LastName", "Age", "PhoneNumber", "Date checled In", "Date Checked out", "RoomNo", "RoomType", "Room Price", "Payment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(AllBookingTable);

        TotalRooms.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        TotalRooms.setText("4");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel5.setText("Total No of Rooms");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel6.setText("Rooms Booked ");

        TotalBooked.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        TotalBooked.setText("4");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel8.setText("Total Payment");

        TotalPayment.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        TotalPayment.setText("4");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel10.setText("Reports");

        ClearDateButton.setBackground(new java.awt.Color(0, 0, 0));
        ClearDateButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ClearDateButton.setForeground(new java.awt.Color(255, 255, 255));
        ClearDateButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\HMS\\clear_32.png")); // NOI18N
        ClearDateButton.setText("Clear");
        ClearDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearDateButtonActionPerformed(evt);
            }
        });

        GoButton.setBackground(new java.awt.Color(0, 0, 0));
        GoButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        GoButton.setForeground(new java.awt.Color(255, 255, 255));
        GoButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\HMS\\go_32.png")); // NOI18N
        GoButton.setText("Go");
        GoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(FirstNameLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(TotalBooked, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TotalRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(ClearDateButton)
                                        .addGap(11, 11, 11)))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(TotalPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(GoButton)
                                        .addGap(194, 194, 194)))))
                        .addContainerGap(152, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(StartingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                        .addComponent(FirstNameLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EndingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalBooked, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EndingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoButton)
                    .addComponent(ClearDateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );

        ReportPage.add(jPanel7, java.awt.BorderLayout.CENTER);

        PagesPanel.add(ReportPage, "card2");

        EmployeePage.setBackground(new java.awt.Color(255, 204, 51));
        EmployeePage.setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());
        EmployeePage.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel5.setOpaque(false);

        FirstNameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel.setText("List Of Employee");

        EmployeeRenameUsername.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        FirstNameLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel1.setText("Employee Password");

        EmployeePassword.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        RegisterEmployee.setBackground(new java.awt.Color(0, 0, 0));
        RegisterEmployee.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        RegisterEmployee.setForeground(new java.awt.Color(255, 255, 255));
        RegisterEmployee.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\HMS\\add_32.png")); // NOI18N
        RegisterEmployee.setText("Register Employee");
        RegisterEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterEmployeeActionPerformed(evt);
            }
        });

        FirstNameLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel6.setText("EmplyeeUserName");

        EmployeeTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        EmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User Name", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(EmployeeTable);

        FirstNameLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel2.setText("Register Employee");

        FirstNameLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel7.setText("EmplyeeUserName");

        EmployeeUsername.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        DeleteEmployee.setBackground(new java.awt.Color(0, 0, 0));
        DeleteEmployee.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        DeleteEmployee.setForeground(new java.awt.Color(255, 255, 255));
        DeleteEmployee.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\HMS\\delete_32.png")); // NOI18N
        DeleteEmployee.setText("Delete Employee");
        DeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEmployeeActionPerformed(evt);
            }
        });

        FirstNameLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel11.setText("Delete Employee");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(RegisterEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(153, 153, 153)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(FirstNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FirstNameLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(80, 80, 80))))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FirstNameLabel1)
                                .addComponent(FirstNameLabel6))
                            .addGap(106, 106, 106)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EmployeePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(EmployeeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(136, 136, 136)
                                    .addComponent(FirstNameLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(EmployeeRenameUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeRenameUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterEmployee)
                    .addComponent(DeleteEmployee))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        EmployeePage.add(jPanel5, java.awt.BorderLayout.NORTH);

        PagesPanel.add(EmployeePage, "card2");

        RoomsPage.setBackground(new java.awt.Color(255, 204, 51));

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Room Number");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("Rooms");

        RoomTypeComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        RoomTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomTypeComboBoxActionPerformed(evt);
            }
        });

        AddRoom.setBackground(new java.awt.Color(0, 0, 0));
        AddRoom.setForeground(new java.awt.Color(255, 255, 255));
        AddRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelBooking/Assets/icons8_add_32.png"))); // NOI18N
        AddRoom.setText("Add");
        AddRoom.setBorder(null);
        AddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoomActionPerformed(evt);
            }
        });

        RoomNoField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        RoomNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomNoFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Room Type");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(RoomNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(RoomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(AddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(jLabel1)))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(RoomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(AddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RoomNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 51));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setToolTipText("");

        RoomTable.setBackground(new java.awt.Color(255, 204, 51));
        RoomTable.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        RoomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Room No", "Room Tpye", "Room Price", "Room Checked"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RoomTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RoomsPageLayout = new javax.swing.GroupLayout(RoomsPage);
        RoomsPage.setLayout(RoomsPageLayout);
        RoomsPageLayout.setHorizontalGroup(
            RoomsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RoomsPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        RoomsPageLayout.setVerticalGroup(
            RoomsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomsPageLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PagesPanel.add(RoomsPage, "card2");

        ProfilePage.setBackground(new java.awt.Color(255, 204, 51));
        ProfilePage.setMaximumSize(new java.awt.Dimension(1306, 727));
        ProfilePage.setPreferredSize(new java.awt.Dimension(1000, 727));
        ProfilePage.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(0, 255, 0));
        jPanel8.setOpaque(false);

        AdminUpdate.setBackground(new java.awt.Color(0, 0, 0));
        AdminUpdate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        AdminUpdate.setForeground(new java.awt.Color(255, 255, 255));
        AdminUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\HMS\\update_48.png")); // NOI18N
        AdminUpdate.setText("UPDATE ");
        AdminUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminUpdateActionPerformed(evt);
            }
        });

        FirstNameLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel3.setText("Admin Old Password");

        AdminUsername.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        FirstNameLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel8.setText("Admin Username");

        FirstNameLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel9.setText("Profiles");

        FirstNameLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel4.setText("Admin New Password");

        FirstNameLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel5.setText("Confirm Password");

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelBooking/Assets/maleADmin_64.png"))); // NOI18N

        FirstNameLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel13.setText("UPDATE PROFILE");

        AdminNewPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        AdminOldPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        AdminConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstNameLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(FirstNameLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FirstNameLabel4)))
                .addGap(97, 97, 97)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminOldPassword)
                    .addComponent(AdminUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(AdminNewPassword)
                    .addComponent(AdminConfirmPassword))
                .addGap(294, 294, 294))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(AdminUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(FirstNameLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNameLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(FirstNameLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstNameLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FirstNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AdminUpdate)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        ProfilePage.add(jPanel8, java.awt.BorderLayout.CENTER);

        PagesPanel.add(ProfilePage, "card2");

        MainPanel.add(PagesPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void GoButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.UpdateDashboardTable();
    }

    protected void ClearDateButtonActionPerformed(ActionEvent evt) {
        this.StartingDate.setDate(null);
        this.EndingDate.setDate(null);
    }

    protected void AdminUpdateActionPerformed(ActionEvent evt) {
        String adminUsername = AdminUsername.getText();
        String Oldpassword = String.valueOf(AdminOldPassword.getPassword());
        String newPassword = String.valueOf(AdminNewPassword.getPassword());
        String ConfirmPassword = String.valueOf(AdminConfirmPassword.getPassword());
        if (adminUsername.length() > 0 && Oldpassword.length() > 0 && newPassword.length() > 0
                && ConfirmPassword.length() > 0) {
            if (!ConfirmPassword.equals(newPassword)) {
                JOptionPane.showMessageDialog(null, "confirm password and new password are not equal", "Error", 1);
            } else {
                int result = clientSocket.updateAdmin(adminUsername, newPassword,Oldpassword);
                if (result > 0) {
                    JOptionPane.showMessageDialog(null, "ADMIN information is Updated Succesfully", "Message", 1);
                    AdminUsername.setText("");
                    AdminOldPassword.setText("");
                    AdminNewPassword.setText("");
                    AdminConfirmPassword.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect username or password", "Message", 1);
                    AdminUsername.setText("");
                    AdminOldPassword.setText("");
                    AdminNewPassword.setText("");
                    AdminConfirmPassword.setText("");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "one or multiple fiedls are empty", "Error", 1);

        }

    }

    protected void RoomNoFieldActionPerformed(ActionEvent evt) {
    }

    protected void AddRoomActionPerformed(ActionEvent evt) {
        Object item = RoomTypeComboBox.getSelectedItem();
        RoomType temp = ((ComboItem) item).getValue();
        String RoomNo = RoomNoField.getText();
        int RoomId = temp.RoomTypeId;
        String msg = clientSocket.addRoom(RoomNo, RoomId);
        this.updateTablesPage();
        JOptionPane.showMessageDialog(null, msg, "Message", 1);
        RoomNoField.setText("");

    }

    protected void RoomTypeComboBoxActionPerformed(ActionEvent evt) {
    }

    protected void DeleteEmployeeActionPerformed(ActionEvent evt) {
        String username = EmployeeRenameUsername.getText();
        if (username.length() > 0) {

            int result = clientSocket.deleteEmployee(username);
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "User has been deleted Successfullt", "Message", 1);
                this.updateEmployee();
            } else {
                JOptionPane.showMessageDialog(null, "Username Doesn't exist", "Message", 1);
                this.updateEmployee();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Field is Empty", "Input Error", 1);

        }
        EmployeeUsername.setText("");
        EmployeePassword.setText("");
        EmployeeRenameUsername.setText("");
    }

    protected void RegisterEmployeeActionPerformed(ActionEvent evt) {
        String username = EmployeeUsername.getText();
        String password = EmployeePassword.getText();

        System.out.println("hello here");
        if (username.length() > 0 && password.length() > 0) {
            
                String msgclient = clientSocket.registerEmployee(username,password);

            JOptionPane.showMessageDialog(null, msgclient, "Message", 1);
            this.updateEmployee();
        } else {
            JOptionPane.showMessageDialog(null, "One Or More Field is Empty", "Input Error", 1);
        }
        
        EmployeeUsername.setText("");
        EmployeePassword.setText("");
        EmployeeRenameUsername.setText("");
    }

    protected void StartingDateActionPerformed(ActionEvent evt) {
    }

    protected void ProfileNavActionPerformed(ActionEvent evt) {
        PagesPanel.removeAll();
        PagesPanel.repaint();
        PagesPanel.revalidate();

        PagesPanel.add(ProfilePage);
        PagesPanel.repaint();
        PagesPanel.revalidate();
    }

    protected void RoomsNavActionPerformed(ActionEvent evt) {



        this.updateTablesPage();
        PagesPanel.removeAll();
        PagesPanel.repaint();
        PagesPanel.revalidate();

        PagesPanel.add(RoomsPage);
        PagesPanel.repaint();
        PagesPanel.revalidate();
    }

    protected void reportNavActionPerformed(ActionEvent evt) {

        PagesPanel.removeAll();
        PagesPanel.repaint();
        PagesPanel.revalidate();

        PagesPanel.add(ReportPage);
        PagesPanel.repaint();
        PagesPanel.revalidate();
    }

    protected void EmployeeNavActionPerformed(ActionEvent evt) {
        
        this.updateEmployee();
        PagesPanel.removeAll();
        PagesPanel.repaint();
        PagesPanel.revalidate();

        PagesPanel.add(EmployeePage);
        PagesPanel.repaint();
        PagesPanel.revalidate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    private javax.swing.JComboBox<ComboItem> RoomTypeComboBox;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRoom;
    private javax.swing.JPasswordField AdminConfirmPassword;
    private javax.swing.JPasswordField AdminNewPassword;
    private javax.swing.JPasswordField AdminOldPassword;
    private javax.swing.JButton AdminUpdate;
    private javax.swing.JTextField AdminUsername;
    private javax.swing.JTable AllBookingTable;
    private javax.swing.JButton ClearDateButton;
    private javax.swing.JButton DeleteEmployee;
    private javax.swing.JButton EmployeeNav;
    private javax.swing.JPanel EmployeePage;
    private javax.swing.JTextField EmployeePassword;
    private javax.swing.JTextField EmployeeRenameUsername;
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JTextField EmployeeUsername;
    private org.jdesktop.swingx.JXDatePicker EndingDate;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JLabel FirstNameLabel1;
    private javax.swing.JLabel FirstNameLabel10;
    private javax.swing.JLabel FirstNameLabel11;
    private javax.swing.JLabel FirstNameLabel12;
    private javax.swing.JLabel FirstNameLabel13;
    private javax.swing.JLabel FirstNameLabel2;
    private javax.swing.JLabel FirstNameLabel3;
    private javax.swing.JLabel FirstNameLabel4;
    private javax.swing.JLabel FirstNameLabel5;
    private javax.swing.JLabel FirstNameLabel6;
    private javax.swing.JLabel FirstNameLabel7;
    private javax.swing.JLabel FirstNameLabel8;
    private javax.swing.JLabel FirstNameLabel9;
    private javax.swing.JButton GoButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel OptionPanel;
    private javax.swing.JPanel PagesPanel;
    private javax.swing.JButton ProfileNav;
    private javax.swing.JPanel ProfilePage;
    private javax.swing.JButton RegisterEmployee;
    private javax.swing.JPanel ReportPage;
    private javax.swing.JTextField RoomNoField;
    private javax.swing.JTable RoomTable;
    private javax.swing.JButton RoomsNav;
    private javax.swing.JPanel RoomsPage;
    private org.jdesktop.swingx.JXDatePicker StartingDate;
    private javax.swing.JLabel TotalBooked;
    private javax.swing.JLabel TotalPayment;
    private javax.swing.JLabel TotalRooms;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton reportNav;
    // End of variables declaration//GEN-END:variables
}
