/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelBooking;

import HotelBooking.Database.DatabaseConn;
import Model.BookRoom;
import Model.Room;
import Model.RoomType;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import ClientSocket.Client;

import java.util.*;
import java.util.Date;
import java.util.List;
import java.sql.*;
import java.net.*;

/**
 *
 * @author Admin
 */



public class HMS extends javax.swing.JFrame {

    public Socket connection = null;

    Client clientSocket = new Client();

    private List<Room> RoomsNotBooked = null;
    private List<BookRoom> RoomsBooked = null;
    private BookRoom checkOutRoom = null; 

    /**
     * 
     * Creates new form HMS
     */
    public HMS() {
        this.RoomsNotBooked = clientSocket.getRoomsNotChecked();
        this.RoomsBooked = clientSocket.getBooking();
        initComponents();
        this.updateCheckInPageTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        OptionPanel = new javax.swing.JPanel();
        checkOutNav = new javax.swing.JButton();
        CheckInNav = new javax.swing.JButton();
        ProfileNav = new javax.swing.JButton();
        PagesPanel = new javax.swing.JPanel();
        CheckInPage = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        FirstNameLabel1 = new javax.swing.JLabel();
        LastNameField = new javax.swing.JTextField();
        FirstNameLabel2 = new javax.swing.JLabel();
        AgeField = new javax.swing.JTextField();
        FirstNameLabel3 = new javax.swing.JLabel();
        PhoneNumberField = new javax.swing.JTextField();
        FirstNameLabel4 = new javax.swing.JLabel();
        FirstNameLabel5 = new javax.swing.JLabel();
        RoomNumberField = new javax.swing.JTextField();
        DateField = new org.jdesktop.swingx.JXDatePicker();
        CheckInButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CheckInTable = new javax.swing.JTable();
        CheckOutPage = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        FirstNameLabel6 = new javax.swing.JLabel();
        FirstNameField1 = new javax.swing.JTextField();
        FirstNameLabel7 = new javax.swing.JLabel();
        LastNameField1 = new javax.swing.JTextField();
        FirstNameLabel8 = new javax.swing.JLabel();
        AgeField1 = new javax.swing.JTextField();
        FirstNameLabel9 = new javax.swing.JLabel();
        PhoneNumberField1 = new javax.swing.JTextField();
        FirstNameLabel10 = new javax.swing.JLabel();
        FirstNameLabel11 = new javax.swing.JLabel();
        SearchRoomField = new javax.swing.JTextField();
        DateField1 = new org.jdesktop.swingx.JXDatePicker();
        CheckOutButton = new javax.swing.JButton();
        SearchRoomBtn = new javax.swing.JButton();
        FirstNameLabel12 = new javax.swing.JLabel();
        DateField2 = new org.jdesktop.swingx.JXDatePicker();
        PriceField = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BookedRoomsTable = new javax.swing.JTable();
        ProfilePage = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        ProfilePanel = new javax.swing.JPanel();
        EmployeeConfirmPassword = new javax.swing.JPasswordField();
        FirstNameLabel17 = new javax.swing.JLabel();
        FirstNameLabel13 = new javax.swing.JLabel();
        EmployeeUsername = new javax.swing.JTextField();
        EmployeeOldPassword = new javax.swing.JPasswordField();
        FirstNameLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        FirstNameLabel18 = new javax.swing.JLabel();
        FirstNameLabel14 = new javax.swing.JLabel();
        EmployeeUpdate = new javax.swing.JButton();
        EmployeeNewPassword = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setPreferredSize(new java.awt.Dimension(1000, 500));
        MainPanel.setLayout(new java.awt.BorderLayout());

        OptionPanel.setBackground(new java.awt.Color(255, 255, 255));
        OptionPanel.setPreferredSize(new java.awt.Dimension(1000, 100));

        checkOutNav.setBackground(new java.awt.Color(0, 0, 0));
        checkOutNav.setForeground(new java.awt.Color(255, 255, 255));
        checkOutNav.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\HMS\\Import_64.png")); // NOI18N
        checkOutNav.setText("CHECK OUT");
        checkOutNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutNavActionPerformed(evt);
            }
        });

        CheckInNav.setBackground(new java.awt.Color(0, 0, 0));
        CheckInNav.setForeground(new java.awt.Color(255, 255, 255));
        CheckInNav.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\HMS\\export_64.png")); // NOI18N
        CheckInNav.setText("CHECK IN");
        CheckInNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInNavActionPerformed(evt);
            }
        });

        ProfileNav.setBackground(new java.awt.Color(0, 0, 0));
        ProfileNav.setForeground(new java.awt.Color(255, 255, 255));
        ProfileNav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelBooking/Assets/icons8_bed_64.png"))); // NOI18N
        ProfileNav.setText("Profile");
        ProfileNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileNavActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OptionPanelLayout = new javax.swing.GroupLayout(OptionPanel);
        OptionPanel.setLayout(OptionPanelLayout);
        OptionPanelLayout.setHorizontalGroup(
            OptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(CheckInNav, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(checkOutNav, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186)
                .addComponent(ProfileNav, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        OptionPanelLayout.setVerticalGroup(
            OptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(OptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOutNav, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckInNav, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProfileNav, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        MainPanel.add(OptionPanel, java.awt.BorderLayout.NORTH);

        PagesPanel.setPreferredSize(new java.awt.Dimension(1000, 500));
        PagesPanel.setLayout(new java.awt.CardLayout());

        CheckInPage.setBackground(new java.awt.Color(255, 204, 51));
        CheckInPage.setPreferredSize(new java.awt.Dimension(1000, 500));
        CheckInPage.setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());
        CheckInPage.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel5.setOpaque(false);

        FirstNameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel.setText("First Name");

        FirstNameField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameFieldActionPerformed(evt);
            }
        });

        FirstNameLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel1.setText("Last Name");

        LastNameField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        FirstNameLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel2.setText("Age");

        AgeField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        FirstNameLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel3.setText("Phone Number");

        PhoneNumberField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        FirstNameLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel4.setText("Date");

        FirstNameLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel5.setText("RoomNo");

        RoomNumberField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        CheckInButton.setBackground(new java.awt.Color(0, 0, 0));
        CheckInButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CheckInButton.setForeground(new java.awt.Color(255, 255, 255));
        CheckInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelBooking/Assets/check_32.png"))); // NOI18N
        CheckInButton.setText("Check In");
        CheckInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInButtonActionPerformed(evt);
            }
        });

        CheckInTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        CheckInTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Room No", "Room Type", "Room Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(CheckInTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(FirstNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameLabel3)
                            .addComponent(FirstNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(FirstNameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RoomNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(FirstNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(CheckInButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoomNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62)
                .addComponent(CheckInButton)
                .addGap(116, 116, 116)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        CheckInPage.add(jPanel5, java.awt.BorderLayout.NORTH);

        PagesPanel.add(CheckInPage, "card2");

        CheckOutPage.setBackground(new java.awt.Color(255, 204, 51));
        CheckOutPage.setMaximumSize(new java.awt.Dimension(1306, 727));
        CheckOutPage.setPreferredSize(new java.awt.Dimension(1000, 500));
        CheckOutPage.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 204, 51));
        jPanel7.setOpaque(false);

        FirstNameLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel6.setText("First Name");

        FirstNameField1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        FirstNameLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel7.setText("Last Name");

        LastNameField1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        FirstNameLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel8.setText("Age");

        AgeField1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        FirstNameLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel9.setText("Phone Number");

        PhoneNumberField1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        FirstNameLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel10.setText("Check In Date");

        FirstNameLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel11.setText("RoomNo");

        SearchRoomField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        CheckOutButton.setBackground(new java.awt.Color(0, 0, 0));
        CheckOutButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CheckOutButton.setForeground(new java.awt.Color(255, 255, 255));
        CheckOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelBooking/Assets/check_32.png"))); // NOI18N
        CheckOutButton.setText("Check Out");
        CheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutButtonActionPerformed(evt);
            }
        });

        SearchRoomBtn.setBackground(new java.awt.Color(0, 0, 0));
        SearchRoomBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SearchRoomBtn.setForeground(new java.awt.Color(255, 255, 255));
        SearchRoomBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelBooking/Assets/search_32.png"))); // NOI18N
        SearchRoomBtn.setText("Search");
        SearchRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRoomBtnActionPerformed(evt);
            }
        });

        FirstNameLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel12.setText("Check In Date");

        DateField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateField2ActionPerformed(evt);
            }
        });

        PriceField.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        PriceField.setText("Total Price");

        BookedRoomsTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        BookedRoomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "FirstName", "LastName", "Age", "PhoneNumber", "DateCheckedIn", "RoomNo", "RoomType", "Room Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(BookedRoomsTable);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(FirstNameLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LastNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(FirstNameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FirstNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNameLabel9)
                                    .addComponent(FirstNameLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AgeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PhoneNumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNameLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FirstNameLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DateField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DateField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckOutButton)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(FirstNameLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchRoomField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchRoomBtn)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchRoomBtn)
                    .addComponent(FirstNameLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchRoomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FirstNameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FirstNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FirstNameLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LastNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FirstNameLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AgeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FirstNameLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PhoneNumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DateField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNameLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DateField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNameLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addComponent(PriceField)
                .addGap(18, 18, 18)
                .addComponent(CheckOutButton)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CheckOutPage.add(jPanel7, java.awt.BorderLayout.CENTER);

        PagesPanel.add(CheckOutPage, "card2");

        ProfilePage.setBackground(new java.awt.Color(255, 204, 51));
        ProfilePage.setMaximumSize(new java.awt.Dimension(1306, 727));
        ProfilePage.setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel8.setBackground(new java.awt.Color(0, 255, 0));
        jPanel8.setMaximumSize(new java.awt.Dimension(1000, 500));
        jPanel8.setMinimumSize(new java.awt.Dimension(100, 500));
        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(1000, 500));

        ProfilePanel.setOpaque(false);

        EmployeeConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        FirstNameLabel17.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel17.setText("Admin New Password");

        FirstNameLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel13.setText("Employee Old  Password");

        EmployeeUsername.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        EmployeeOldPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        FirstNameLabel16.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel16.setText("Confirm Password");

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelBooking/Assets/maleADmin_64.png"))); // NOI18N

        FirstNameLabel18.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        FirstNameLabel18.setText("UPDATE PROFILE");

        FirstNameLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FirstNameLabel14.setText("Employee Username");

        EmployeeUpdate.setBackground(new java.awt.Color(0, 0, 0));
        EmployeeUpdate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        EmployeeUpdate.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\HMS\\update_48.png")); // NOI18N
        EmployeeUpdate.setText("UPDATE ");
        EmployeeUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeUpdateActionPerformed(evt);
            }
        });

        EmployeeNewPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout ProfilePanelLayout = new javax.swing.GroupLayout(ProfilePanel);
        ProfilePanel.setLayout(ProfilePanelLayout);
        ProfilePanelLayout.setHorizontalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanelLayout.createSequentialGroup()
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfilePanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FirstNameLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FirstNameLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmployeeNewPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeeConfirmPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ProfilePanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProfilePanelLayout.createSequentialGroup()
                                .addComponent(FirstNameLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(EmployeeOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProfilePanelLayout.createSequentialGroup()
                                .addComponent(FirstNameLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmployeeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EmployeeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(ProfilePanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FirstNameLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        ProfilePanelLayout.setVerticalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FirstNameLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23)
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfilePanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(EmployeeConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfilePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(FirstNameLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EmployeeUpdate)
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(ProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(ProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ProfilePageLayout = new javax.swing.GroupLayout(ProfilePage);
        ProfilePage.setLayout(ProfilePageLayout);
        ProfilePageLayout.setHorizontalGroup(
            ProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ProfilePageLayout.setVerticalGroup(
            ProfilePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PagesPanel.add(ProfilePage, "card2");

        MainPanel.add(PagesPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );

        MainPanel.getAccessibleContext().setAccessibleName("");
        MainPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInButtonActionPerformed
        // TODO add your handling code here:

        

        if(this.AgeField.getText().length()>0 && this.FirstNameField.getText().length()>0
            && this.LastNameField.getText().length()>0 && this.PhoneNumberField.getText().length()>0
            && this.DateField.getDate()!=null && this.RoomNumberField.getText().length()>0

        ){
            try{
                
                String Fname = this.FirstNameField.getText();
                String Lname = this.LastNameField.getText();
                int Age = Integer.parseInt(this.AgeField.getText());
                String PhoneNumber = this.PhoneNumberField.getText();
                Date date = this.DateField.getDate();
                String RoomNo = this.RoomNumberField.getText();

                String msg = this.clientSocket.CheckIn(Fname, Lname, Age, PhoneNumber, date, RoomNo);
                this.updateCheckInPageTable();
                JOptionPane.showMessageDialog(null,msg,"Message",1);

                this.FirstNameField.setText("");
                this.LastNameField.setText("");
                this.AgeField.setText("");
                this.PhoneNumberField.setText("");
                this.RoomNumberField.setText("");
                this.DateField.setDate(null);

            }
            catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,"Make SURE THE Age Is An Integer","Input Error",1);
            }
        }else{
            JOptionPane.showMessageDialog(null,"One Or MoreField Is Empty","Input Error",1);

        }
        

        
    }//GEN-LAST:event_CheckInButtonActionPerformed

    private void CheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutButtonActionPerformed
        // TODO add your handling code here:
        if(checkOutRoom!=null){
            clientSocket.CheckOut(checkOutRoom);

            this.updateBookedRoomsTable();
            JOptionPane.showMessageDialog(null, "Checked Out Successfull", "Success", 1);
            this.SearchRoomField.setText("");
            this.FirstNameField1.setText("");
            this.LastNameField1.setText("");
            this.AgeField1.setText("");
            this.PhoneNumberField1.setText("");
            this.DateField1.setDate(null);
            this.DateField2.setDate(null);
            this.PriceField.setText("Total Price");


        }else{
            JOptionPane.showMessageDialog(null, "No Information is Provided", "Error", 1);
        }
    }//GEN-LAST:event_CheckOutButtonActionPerformed

    private void SearchRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRoomBtnActionPerformed
        // TODO add your handling code here:

        if(SearchRoomField.getText().length()>0){
            System.out.println("hellow got here");
            String RoomNo = SearchRoomField.getText();
            AbstractMap.Entry<BookRoom, String> map = clientSocket.getBookedRoom(RoomNo);
            String msg = map.getValue();
            checkOutRoom = map.getKey();
            if(checkOutRoom!=null){
                this.FirstNameField1.setText(checkOutRoom.FirstName);
                this.LastNameField1.setText(checkOutRoom.LastName);
                this.AgeField1.setText(String.valueOf(checkOutRoom.Age));
                this.PhoneNumberField1.setText(checkOutRoom.PhoneNumber);
                this.DateField1.setDate(checkOutRoom.DateCheckedIn);
                this.DateField2.setDate(checkOutRoom.DateCheckedOut);
            }else{
                JOptionPane.showMessageDialog(null,msg,"Input Error",1);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Room No is Empty Is Empty","Input Error",1);
        }

        
    }//GEN-LAST:event_SearchRoomBtnActionPerformed

    private void DateField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateField2ActionPerformed
        // TODO add your handling code here:
       
        if(checkOutRoom!=null){
            java.util.Date checkIn = checkOutRoom.DateCheckedIn;
            Date checkout = DateField2.getDate();
            int days = getDifferenceDays(checkIn,checkout);
            checkOutRoom.DateCheckedOut = new java.sql.Date(checkout.getTime());
            
            System.out.println("days is here "+days+" "+checkOutRoom.RoomTypePrice);
            if (days==0){
                checkOutRoom.payment = checkOutRoom.RoomTypePrice*days;
                this.PriceField.setText("TOTAL PRICE IS "+String.valueOf(checkOutRoom.payment) + " BIRR");
            }
            else if(days>0){
                checkOutRoom.payment = checkOutRoom.RoomTypePrice*days;
                this.PriceField.setText("TOTAL PRICE IS "+String.valueOf(checkOutRoom.payment) + " BIRR");
            }
            else{
                JOptionPane.showMessageDialog(null,"check out data can not be negative","Input Error",1);
                this.DateField2.setDate(checkIn);
                checkOutRoom.DateCheckedOut = new java.sql.Date(checkout.getTime());
            }
        }else{
            JOptionPane.showMessageDialog(null,"Please Full the Other Forms First","Input Error",1);
            this.DateField2.setDate(null);
            checkOutRoom.DateCheckedOut = null;
        }
    }//GEN-LAST:event_DateField2ActionPerformed

    private void EmployeeUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeUpdateActionPerformed
        // TODO add your handling code here:
        String adminUsername = EmployeeUsername.getText();
        String Oldpassword = String.valueOf(EmployeeOldPassword.getPassword());
        String newPassword = String.valueOf(EmployeeNewPassword.getPassword());
        String ConfirmPassword = String.valueOf(EmployeeConfirmPassword.getPassword());
        if (adminUsername.length() > 0 && Oldpassword.length() > 0 && newPassword.length() > 0
                && ConfirmPassword.length() > 0) {
            if (!ConfirmPassword.equals(newPassword)) {
                JOptionPane.showMessageDialog(null, "confirm password and new password are not equal", "Error", 1);
            } else {
                int result = clientSocket.updateEmployee(adminUsername, newPassword,Oldpassword);
                if (result > 0) {
                    JOptionPane.showMessageDialog(null, "Employee information is Updated Succesfully", "Message", 1);
                    EmployeeUsername.setText("");
                    EmployeeOldPassword.setText("");
                    EmployeeNewPassword.setText("");
                    EmployeeConfirmPassword.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect username or password", "Message", 1);
                    EmployeeUsername.setText("");
                    EmployeeOldPassword.setText("");
                    EmployeeNewPassword.setText("");
                    EmployeeConfirmPassword.setText("");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "one or multiple fiedls are empty", "Error", 1);

        }

    }//GEN-LAST:event_EmployeeUpdateActionPerformed

    private void ProfileNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileNavActionPerformed
        // TODO add your handling code here:
        PagesPanel.removeAll();
        PagesPanel.repaint();
        PagesPanel.revalidate();

        PagesPanel.add(ProfilePage);
        PagesPanel.repaint();
        PagesPanel.revalidate();
    }//GEN-LAST:event_ProfileNavActionPerformed

    private void FirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameFieldActionPerformed

    public int getDifferenceDays(Date d1, Date d2) {
        int daysdiff = 0;
        long diff = d2.getTime() - d1.getTime();
        long diffDays = diff / (24 * 60 * 60 * 1000) + 1;
        daysdiff = (int) diffDays;
        return daysdiff;
    }

    private void checkOutNavActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_checkOutNavActionPerformed


        this.updateBookedRoomsTable();


        checkOutRoom = null;
        SearchRoomField.setText("");
        FirstNameField1.setText("");
        LastNameField1.setText("");
        AgeField1.setText("");
        PhoneNumberField1.setText("");
        DateField1.setDate(null);
        DateField2.setDate(null);
        PriceField.setText("");

        
        // TODO add your handling code here:
        PagesPanel.removeAll();
        PagesPanel.repaint();
        PagesPanel.revalidate();

        PagesPanel.add(CheckOutPage);
        PagesPanel.repaint();
        PagesPanel.revalidate();

        
    }// GEN-LAST:event_checkOutNavActionPerformed

    //CheckInNavActionPerformed

    public void updateBookedRoomsTable(){
        this.RoomsBooked =  this.clientSocket.getBookedRooms();

        while(BookedRoomsTable.getRowCount()>0){
                ((DefaultTableModel) BookedRoomsTable.getModel()).removeRow(0);
            }

        DefaultTableModel model = (DefaultTableModel) BookedRoomsTable.getModel();
        
        
        for (BookRoom b: this.RoomsBooked){
            model.addRow(new Object[] { b.FirstName,b.LastName, b.Age, b.PhoneNumber,b.DateCheckedIn,b.RoomNo,b.RoomTypeName,b.RoomTypePrice});
        }
    }

    public void updateCheckInPageTable(){
        this.RoomsNotBooked =  this.clientSocket.getRoomsNotChecked();

        while(CheckInTable.getRowCount()>0){
                ((DefaultTableModel) CheckInTable.getModel()).removeRow(0);
            }

        DefaultTableModel model = (DefaultTableModel) CheckInTable.getModel();
        
        
        for (Room r: this.RoomsNotBooked){
            model.addRow(new Object[] { r.RoomNo,r.RoomTypeName, r.RoomTypePrice});
        }
    }
    private void CheckInNavActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CheckInNavActionPerformed
        // TODO add your handling code here:
        this.updateCheckInPageTable();
        System.out.println("this is checkIn");
        PagesPanel.removeAll();
        PagesPanel.repaint();
        PagesPanel.revalidate();
        PagesPanel.add(CheckInPage);
        PagesPanel.repaint();
        PagesPanel.revalidate();
        

    }// GEN-LAST:event_CheckInNavActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeField;
    private javax.swing.JTextField AgeField1;
    private javax.swing.JTable BookedRoomsTable;
    private javax.swing.JButton CheckInButton;
    private javax.swing.JButton CheckInNav;
    private javax.swing.JPanel CheckInPage;
    private javax.swing.JTable CheckInTable;
    private javax.swing.JButton CheckOutButton;
    private javax.swing.JPanel CheckOutPage;
    private org.jdesktop.swingx.JXDatePicker DateField;
    private org.jdesktop.swingx.JXDatePicker DateField1;
    private org.jdesktop.swingx.JXDatePicker DateField2;
    private javax.swing.JPasswordField EmployeeConfirmPassword;
    private javax.swing.JPasswordField EmployeeNewPassword;
    private javax.swing.JPasswordField EmployeeOldPassword;
    private javax.swing.JButton EmployeeUpdate;
    private javax.swing.JTextField EmployeeUsername;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JTextField FirstNameField1;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JLabel FirstNameLabel1;
    private javax.swing.JLabel FirstNameLabel10;
    private javax.swing.JLabel FirstNameLabel11;
    private javax.swing.JLabel FirstNameLabel12;
    private javax.swing.JLabel FirstNameLabel13;
    private javax.swing.JLabel FirstNameLabel14;
    private javax.swing.JLabel FirstNameLabel16;
    private javax.swing.JLabel FirstNameLabel17;
    private javax.swing.JLabel FirstNameLabel18;
    private javax.swing.JLabel FirstNameLabel2;
    private javax.swing.JLabel FirstNameLabel3;
    private javax.swing.JLabel FirstNameLabel4;
    private javax.swing.JLabel FirstNameLabel5;
    private javax.swing.JLabel FirstNameLabel6;
    private javax.swing.JLabel FirstNameLabel7;
    private javax.swing.JLabel FirstNameLabel8;
    private javax.swing.JLabel FirstNameLabel9;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JTextField LastNameField1;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel OptionPanel;
    private javax.swing.JPanel PagesPanel;
    private javax.swing.JTextField PhoneNumberField;
    private javax.swing.JTextField PhoneNumberField1;
    private javax.swing.JLabel PriceField;
    private javax.swing.JButton ProfileNav;
    private javax.swing.JPanel ProfilePage;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JTextField RoomNumberField;
    private javax.swing.JButton SearchRoomBtn;
    private javax.swing.JTextField SearchRoomField;
    private javax.swing.JButton checkOutNav;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
